"""add refresh_tokens table

Revision ID: b1cc07891b37
Revises: 2f9c7a935d76
Create Date: 2026-08-29 20:07:40.098363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cc07891b37'
down_revision: Union[str, None] = '2f9c7a935d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['public.refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='public')
    op.create_index(op.f('ix_public_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###
    # Autogenerate also proposed dropping alembic_version and re-qualifying
    # the users.tenant_id FK's schema — both cosmetic artifacts of
    # include_schemas reflection, not real changes; removed by hand.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_refresh_tokens_user_id'), table_name='refresh_tokens', schema='public')
    op.drop_index(op.f('ix_public_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='public')
    op.drop_table('refresh_tokens', schema='public')
    # ### end Alembic commands ###
